FROM centos:7

MAINTAINER samurai829

RUN yum -y install openssh-server

RUN yum -y install mysql

RUN yum -y install epel-release && \
    yum -y install python-pip && \
    pip install awscli

RUN useradd remote_user && \
    echo "remote_user:1234" | chpasswd && \
    mkdir /home/remote_user/.ssh && \
    chmod 700 /home/remote_user/.ssh

COPY remote-key.pub /home/remote_user/.ssh/authorized_keys

RUN chown remote_user:remote_user -R /home/remote_user/.ssh/

RUN /usr/bin/ssh-keygen -A

CMD ["/usr/sbin/sshd", "-D"]